services:
  omniroute:
    image: diegosouzapw/omniroute:latest
    container_name: omniroute
    restart: unless-stopped
    stop_grace_period: 40s
    env_file:
      - .env
    ports:
      - "20128:20128"
    volumes:
      - omniroute-data:/app/data

volumes:
  omniroute-data:
